/**
 * SHARED TAILWIND CONFIGURATION (CDN MODE)
 */

tailwind.config = {
    theme: {
        screens: {
            'sm': '481px',
            'md': '769px',
            'lg': '1025px',
            'xl': '1441px',
        },
        extend: {
            fontFamily: {
                urbanist: ['Urbanist', 'sans-serif'],
            },
            fontSize: {
                'display': ['48px', { lineHeight: '1' }],
                'button-lg': ['32px', { lineHeight: '40px' }],
                'h1': ['36px', { lineHeight: '44px' }],
                'h2': ['30px', { lineHeight: '38px' }],
                'h3': ['24px', { lineHeight: '32px' }],
                'body-lg': ['18px', { lineHeight: '28px' }],
                'body': ['16px', { lineHeight: '24px' }],
                'body-sm': ['14px', { lineHeight: '20px' }],
                'body-xs': ['12px', { lineHeight: '16px' }],
                'label': ['14px', { lineHeight: '18px' }],
                'overline': ['12px', { lineHeight: '16px' }],
                'button': ['14px', { lineHeight: '20px' }],
                'link': ['14px', { lineHeight: '20px' }],
                'h1-mobile': ['30px', { lineHeight: '38px' }],
                'h2-mobile': ['26px', { lineHeight: '32px' }],
                'h3-mobile': ['22px', { lineHeight: '28px' }],
                'h1-fluid': ['clamp(30px, 4vw, 36px)', { lineHeight: '1.2' }],
                'h2-fluid': ['clamp(26px, 3vw, 30px)', { lineHeight: '1.2' }],
                'h3-fluid': ['clamp(22px, 2.5vw, 24px)', { lineHeight: '1.2' }],
                // Icon Sizes
                'icon-xs': '12px',
                'icon-sm': '16px',
                'icon-md': '20px',
                'icon-lg': '24px',
                'icon-xl': '32px',
                'icon-xxl': '48px',
                'checkbox-sm': '16px',
                'checkbox-md': '22px',
                'checkbox-lg': '28px',
            },
            fontWeight: {
                'light': '300',
                'regular': '400',
                'medium': '500',
                'semibold': '600',
            },
            lineHeight: {
                'h1': '44px',
                'h2': '38px',
                'h3': '32px',
                'body': '24px',
                'body-lg': '28px',
                'body-sm': '20px',
                'body-xs': '16px',
                'label': '18px',
                'overline': '16px',
                'button': '20px',
                'link': '20px',
            },
            spacing: {
                'heading-top': '32px',
                'heading-bottom': '8px',
                'paragraph': '16px',
                '4': '4px',
                '8': '8px',
                '12': '12px',
                '16': '16px',
                '20': '20px',
                '24': '24px',
                '32': '32px',
                '40': '40px',
                '48': '48px',
                // Icon Gaps
                'icon-xs': '4px',
                'icon-sm': '8px',
                'icon-md': '12px',
                'icon-lg': '20px',
            },
            colors: {
                // page/default removed as requested
                'green-primary': '#03683D',
                'green-secondary': '#058C53',
                'green-hover-icons': '#BEE0D2',
                'green-hover-text': '#E3F1EB',
                'black': '#121212',
                'white': '#FCFCFC',
                'grey-primary': '#878787',
                'grey-secondary': '#D9D9D9',
                'grey-tertiary': '#EDEDED',
                'link-visited': '#4C1D95',
                'red-primary': '#B1242F',
                'red-secondary': '#C94A55',
                // Icon Colors
                'icon-primary': '#03683D',
                'icon-secondary': '#878787',
                'icon-muted': '#D9D9D9',
                'icon-danger': '#B1242F',
                'icon-success': '#03683D',
                'icon-on-dark': '#FCFCFC',
            },
            boxShadow: {
                'btn-default': '0 6px 14px rgba(135, 135, 135, 0.20)',
                'btn-hover': '0 18px 36px rgba(190, 224, 210, 0.40), 0 6px 18px rgba(135, 135, 135, 0.15)',
                'btn-active': '0 4px 10px rgba(0, 0, 0, 0.2)',
                'btn-hover-active': '0 4px 12px rgba(5, 140, 83, 0.2)',
                'btn-glow': '0 20px 40px rgba(16, 185, 129, 0.22)',
            },
            borderRadius: {
                'none': '0',
                'xs': '6px',
                'sm': '8px',
                'md': '12px',
                'lg': '16px',
                'xl': '24px',
                'btn': '12px',
                'full': '9999px',
            },
            opacity: {
                'muted': '0.80',
                'semi': '0.50',
                'faint': '0.10',
            },
            scale: {
                'hover': '1.02',
                'press': '0.98',
                'press-deep': '0.92',
            },
            zIndex: {
                'base': '0',
                'dropdown': '1000',
                'sticky': '1100',
                'overlay': '2000',
                'modal': '2100',
                'popover': '2200',
                'tooltip': '3000',
            },
            maxWidth: {
                'standard': '1280px',
                'wide': '1440px',
                'narrow': '768px',
                'readable': '65ch',
            },
            borderWidth: {
                'thin': '1px',
                'standard': '2px',
                'thick': '4px',
                // Icon Strokes
                'icon-stroke-thin': '1px',
                'icon-stroke-default': '1.5px',
                'icon-stroke-bold': '2px',
            },
            transitionDuration: {
                '400': '400ms',
                'default': '400ms',
            },
            transitionTimingFunction: {
                'button-ease': 'cubic-bezier(0.16, 1, 0.3, 1)',
                'premium': 'cubic-bezier(0.16, 1, 0.3, 1)',
            },
            translate: {
                'lift': '-3px',
                'lift-subtle': '-1px',
                'press': '1px',
            },
            width: {
                'btn-lg': '380px',
                'btn-icon': '94px',
                'icon-xs': '12px',
                'icon-sm': '16px',
                'icon-md': '20px',
                'icon-lg': '24px',
                'icon-xl': '32px',
                'icon-xxl': '48px',
                'checkbox-sm': '16px',
                'checkbox-md': '22px',
                'checkbox-lg': '28px',
            },
            height: {
                'btn-lg': '94px',
                'btn-icon': '94px',
                'icon-xs': '12px',
                'icon-sm': '16px',
                'icon-md': '20px',
                'icon-lg': '24px',
                'icon-xl': '32px',
                'icon-xxl': '48px',
                'checkbox-sm': '16px',
                'checkbox-md': '22px',
                'checkbox-lg': '28px',
            },
            ringWidth: {
                'DEFAULT': '4px',
                'subtle': '2px',
            },
            ringColor: {
                'DEFAULT': '#121212',
            },
            ringOpacity: {
                'DEFAULT': '1',
            }
        }
    }
}
